### ISSUE TITLE
Création du compte et déploiement de l'application frontend au niveau de vercel.

### ISSUE THREAD

**Issue by dofbi** [DSsenegal/app-snpay#10]

**Comment by dofbi** [comment]
Hello @zlorgoncho1 Job done ?
Si oui quel est l'adresse ?

**Comment by zlorgoncho1** [comment]
Hello @dofbi, je viens de déployer le front avec vercel. Voici le lien: [Sandiara Market](https://sandiara-market.vercel.app/)
En déployant sur vercel, j'ai remarqué que lorsqu'on fait l'installation avec `pnpm`, les packages de saleor ne s'installent pas correctement. Donc j'ai utilisé `npm`. Je vais mettre à jour le fichier `package.json` dans ce sens.
Je passe à l'automatisation de la pipeline de déploiement vercel qui s'executera à chaque commit au niveau du front sur la branche main.
