### ISSUE TITLE
Trouver une manière de résoudre les conflits lors de la synchronisation.

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/app-snpay#29]
Il y'a eu des conflits lors de la synchronisation. Il s'agit d'une erreur à corriger.

![Image](https://github.com/user-attachments/assets/47116bb9-79b2-4897-9706-a25d98a2b7d0)

**Comment by zlorgoncho1** [comment]
Hello @dofbi , Je vais voir est ce qu'il n'y a pas un moyen d'éviter ces conflits là. Parce que sur le repository principal, il n'y a pas de conflit.

**Comment by zlorgoncho1** [comment]
> git remote add upstream https://github.com/DSsenegal/app-snpay.git
> git fetch upstream
> git checkout main
> git merge upstream/main --allow-unrelated-histories
> git push origin main

**Comment by zlorgoncho1** [comment]
J'ai effectué, ces changements, mais le merge ne s'effectue pas à cause des historiques de commits qui diffèrent entre les deux projets.

**Comment by dofbi** [comment]
L'historique à fixer manuellement ou delete le repo et restart

> J'ai effectué, ces changements, mais le merge ne s'effectue pas à cause des historiques de commits qui diffèrent entre les deux projets.

**Comment by zlorgoncho1** [comment]
D'accord, j'applique et je vous reviens.

**Comment by zlorgoncho1** [comment]
@dofbi , l'erreur est toujours présent à cause du fichier de synchronisation que j'ai ajouté au niveau du repo que déploie netlify. Mais en faisant des recherches sur chat, j'ai essayé ceci à mon niveau qui a marché. J'ignore qu'est ce que ça va donner lors que vous allez merge un PR. Il règle les conflits en donnant la priorité au upstream.

```sh
git remote add upstream https://github.com/DSsenegal/app-snpay.git
git fetch upstream
git merge upstream/main --strategy-option theirs --allow-unrelated-histories
git push origin main
```


![Image](https://github.com/user-attachments/assets/eb4719f4-f89b-4a40-a1fb-e4770227b8b7)

**Comment by dofbi** [comment]
Ok lance un test avec la création d'un issue manuellement

**Comment by zlorgoncho1** [comment]
Il y'a eu un commit sur main et l'application s'est synchronisé sans mon intervention.

![Image](https://github.com/user-attachments/assets/2e8d684d-be9d-46de-a9d3-953d5d505f79)
