### ISSUE TITLE
App installation failed

### ISSUE THREAD

**Issue by honorableCon** [DSsenegal/app-snpay#31]
- Sur vercel, les serverless functions peuvent pas créer le fichier d'authentification
- Sur Netlify, il manque juste les variables d'environments (se baser sur .env.example)

**Comment by zlorgoncho1** [comment]
Hello @honorableCon, voici les env que j'ai trouvé dans le fichier env.example . Merci de me donner les valeurs exactes à mettre.

```sh
APP_IFRAME_BASE_URL=
APP_API_BASE_URL=
APP_GRAPHQL_URL=
DEXCHANGE_MARCHANT_LINK=
```

**Comment by zlorgoncho1** [comment]
J'ai mis à jour les variable d'environnement. Mais cette erreur persiste.

![Image](https://github.com/user-attachments/assets/39fa9577-2267-4f37-91c5-224bb4883564)

**Comment by honorableCon** [comment]
Je viens de le deployé sur render, effectivement c'était une limitation des hebergeurs.
[Live app](https://senpay.onrender.com)

@dofbi @zlorgoncho1

**Comment by dofbi** [comment]
Installation de l'application ok 👍🏾 
@honorableCon ajoute les information de configuration 🙏🏾 

![Capture d’écran du 2024-07-16 11-35-09](https://github.com/user-attachments/assets/b9cc3c96-a93d-4f8a-90a9-f5820fc4e384)

**Comment by zlorgoncho1** [comment]
Hello @dofbi , voici de potentiels limitations pouvant arriver du coté de render:

![Image](https://github.com/user-attachments/assets/872ecebd-594c-44ca-bc2b-36905ce9c499)

Cela signifie que l'instance gratuite de l'application est configurée pour se mettre en veille après une période d'inactivité. Lorsqu'une demande est effectuée après cette période d'inactivité, l'instance doit d'abord se réveiller et redémarrer, ce qui peut prendre du temps, souvent autour de 50 secondes ou plus, avant que la demande puisse être traitée. En réalité les instances utilisés dans l'offre gratuite sont juste des serverless avec un cold boot pouvant aller à 50 secondes.

**Comment by dofbi** [comment]
@zlorgoncho1 
Merci pour l'update, pour l'app finalement quel est l'emplacement de notre serveur ?

**Comment by dofbi** [comment]
hello @zlorgoncho1 
J'ai fait un test de https://sandiara-market. onrender.com, il est très lent à run. Pouvons-nous garder le netlify aussi up 🙏

**Comment by zlorgoncho1** [comment]
> hello @zlorgoncho1 J'ai fait un test de https://sandiara-market. onrender.com, il est très lent à run. Pouvons-nous garder le netlify aussi up 🙏

Oui je l'ai redéployé sur netlify.



> @zlorgoncho1 Merci pour l'update, pour l'app finalement quel est l'emplacement de notre serveur ?

Notre server est sur Francfort.
