### ISSUE TITLE
Redéployer l'application sn-pay sur render

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/app-snpay#41]
D'après les recherches de @honorableCon ainsi que les tests qu'il a eu à faire, il y'avait des limitations coté netlify concernant le déploiement de l'app-snpay. Je vais alors dans ce sens, redéployer l'application sur rende, la solution proposée par @honorableCon .

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
Nous devons avoir une documentation de nos différentes limitation pour l'application chez

- vercel
- netlify
- render

**Comment by zlorgoncho1** [comment]
Voici les logs du déploiement sur Render.

![Image](https://github.com/user-attachments/assets/4a23539e-8b9f-4a08-b7eb-9109c87d5e27)

**Comment by zlorgoncho1** [comment]
L'application s'est installé avec succès.

![Image](https://github.com/user-attachments/assets/2315ca59-8668-41c2-9b04-7e16924b96a1)

**Comment by zlorgoncho1** [comment]
> Hello [@zlorgoncho1](https://github.com/zlorgoncho1) Nous devons avoir une documentation de nos différentes limitation pour l'application chez
> 
> * vercel
> * netlify
> * render

Hello @dofbi , Voici les limitations que nous avons eu:

- Vercel: Il faut passer premium  pour déployer des projets présents dans des organisations sur github. Il y'a aussi un quota de déploiement à ne pas déployer. Nous avons atteint ce quota très vite à cause de mon cron qui vérifier et déployer directement sur vercel tous les 5 minutes.

- Netlify: Limitation des services backends. Permet un type de déploiement statique avec Next JS.
