### ISSUE TITLE
Checker les quantité et les prix

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/app-snpay#45]
@honorableCon , @dofbi , @mass-gueye 
Savez vous à quoi sert cette valeur ?

![Image](https://github.com/user-attachments/assets/6fa1b4cd-3212-456f-b288-2a0289f224b1)

J'étais en train de rechecker les stocks. Et y'a certains produit qui n'ont pas cette valeur définie.

**Comment by mass-gueye** [comment]
> @honorableCon , @dofbi , @mass-gueye Savez vous à quoi sert cette valeur ?
> 
> ![Image](https://private-user-images.githubusercontent.com/57920555/349700783-6fa1b4cd-3212-456f-b288-2a0289f224b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjExMzEsIm5iZiI6MTcyMTMyMDgzMSwicGF0aCI6Ii81NzkyMDU1NS8zNDk3MDA3ODMtNmZhMWI0Y2QtMzIxMi00NTZmLWIyODgtMmEwMjg5ZjIyNGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDE2NDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMmNiNjg0Mjk2MTM4NGU1NzRiODhmMDYxZGQ2ZDNiMzNhYjQxM2U3ZDhmNGFiMzQ3YTQyZmJhMDA0MmE5MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mww8eEqXfGXEIs2otdvtz-UeOT0v23PRsyJ03y7P8Uk)
> 
> J'étais en train de rechecker les stocks. Et y'a certains produit qui n'ont pas cette valeur définie.

A SKU (Stock Keeping Unit) est un code alphanumérique unique utilisé pour identifier et différencier les produits et leurs variantes. Les SKU permettent aux entreprises de suivre les quantités de stock disponibles, les ventes et d'autres métriques pour chaque variante de produit. Chaque SKU encode des détails importants comme la marque, la catégorie, la taille, et la couleur, ce qui facilite la gestion de l'inventaire et l'accomplissement des commandes【12†source】【13†source】.

Pour plus de détails, vous pouvez consulter cet article de Shopify : [What is a SKU?](https://help.shopify.com/en/manual/shipping/shopify-fulfillment-network/inbound-transfers/preparing-your-products/adding-product-details/adding-skus).
