### ISSUE TITLE
Ajouter la version et un nom différent pour app Senpay

### ISSUE THREAD

**Issue by dofbi** [DSsenegal/app-snpay#47]
Hello @honorableCon 
Pour distinguer la version en ligne officielle de la version en cours de test peux, tu changeais le nom de l'app

![Image](https://github.com/user-attachments/assets/c21eaa2e-9c13-4b63-bb12-72a28ddcf826)

**Comment by honorableCon** [comment]
je supprime l'autre

**Comment by honorableCon** [comment]
les deux sont les mêmes y'a juste le compte  deploiement qui diffère
