### ISSUE TITLE
Installer la dernière version de app-snpay dans le store après la modification des variables d'environnements

### ISSUE THREAD

**Issue by zlorgoncho1** [DSsenegal/app-snpay#49]
Hello @honorableCon , j'ai mis à jour les variables d'environnements et j'ai redéployé. N'hésite pas à checker.

![Image](https://github.com/user-attachments/assets/f56c0933-2dac-4399-ade5-4e7aa20b34fc)

**Comment by honorableCon** [comment]
Good !
