### ISSUE TITLE
Création d'un endpoint pour le checkout et la création de commande

### ISSUE THREAD

**Issue by mass-gueye** [DSsenegal/app-snpay#54]
Je propose d'avoir un endpoint à notre API snpay pour gérer le processus de checkout et créer une commande. Ce endpoint doit accepter les détails nécessaires pour compléter une commande et la sauvegarder dans notre système.

**Comment by honorableCon** [comment]
D'accord @mass-gueye, je vais te fournir ça today

**Comment by mass-gueye** [comment]
> D'accord [@mass-gueye](https://github.com/mass-gueye), je vais te fournir ça today

Merci d'avance @honorableCon

**Comment by honorableCon** [comment]
@mass-gueye le payload

```json
{
  "checkoutId": "",
  "saleorDomain": "xxxxx.saleor.cloud"
}

**Comment by mass-gueye** [comment]
@dofbi

**Comment by honorableCon** [comment]
le endpoint : 
baseUrl/api/checkout

test url : https://senpay.onrender.com/api/checkout
