### ISSUE TITLE
Sandiara Market Core Backend & Dashboard Deployment

### ISSUE THREAD

**Issue by dofbi** [DSsenegal/app-snpay#6]

**Comment by zlorgoncho1** [comment]
Bonjour @dofbi 
J'ai besoin des accès admin du repository pour ajouter les tokens de configuration notamment le token vercel dans un premier temps.

**Comment by dofbi** [comment]
Hello @zlorgoncho1 
Quel repo ?

**Comment by zlorgoncho1** [comment]
Le repository [sandiara-market](https://github.com/DSsenegal/sandiara-market)

**Comment by dofbi** [comment]
@zlorgoncho1 
Je viens de te rajouter dans la Team admin
