### ISSUE TITLE
Ajouter des données aléatoire au niveau du dashboard Sandiara Market

### ISSUE THREAD

**Issue by dofbi** [DSsenegal/app-snpay#9]

**Comment by dofbi** [comment]
Hello Team @zlorgoncho1 @honorableCon @mass-gueye @DSsenegal/do 
Je viens de Clear la database pour avoir un frech start

Donc si vous avez besoin de faire des tests loger vous sur l'autre store en attendant de bien préparer ce store

**Comment by zlorgoncho1** [comment]
Hello @dofbi , je viens de déployer le front avec vercel. Voici le lien: [Sandiara Market](https://sandiara-market.vercel.app)
En déployant sur vercel, j'ai remarqué que  lorsqu'on fait l'installation avec `pnpm`, les packages de saleor ne s'installent pas correctement. Donc j'ai utilisé `npm`. Je vais mettre à jour le fichier `package.json` dans ce sens.
Je vais implémenter une pipeline automatique de déploiement qui va déployer sur vercel à chaque fois qu'on réalise un commit du front sur la branche main.

**Comment by zlorgoncho1** [comment]
Hello @dofbi, J'ai ajouté quelques produits.

![Image](https://github.com/DSsenegal/app-snpay/assets/57920555/ed421fa8-0b1c-44d6-854c-07486cbfa8df)

**Comment by dofbi** [comment]
Great @zlorgoncho1 👍🏾 
Encore plus de données pour tester, la pagination et toutes les catégories.
Merci
